### ISSUE TITLE
[CONSOLE] Assorted Visual Bug Fixes

### ISSUE THREAD

**Issue by vmichalik** [superfluid-finance/superfluid-console#46]
**Task List**

- [x] Vertical centring of Superfluid logo in top left of Console
- [ ] Change interactable icons in page headers to buttons or green links
- [x] Add address to header of Account and Super App pages, and remove from table
- [x] Move copy page link button next to breadcrumbs

**Comment by Mikkoun** [comment]
* Show token symbol before balance.
* Almost every page has a grid at the start of the page that is broken.

**Comment by Mikkoun** [comment]
btw @vmichalik, don't you like the icons? Imo it looks nice and clean like this. If you have interacted with the icon once then you will remember what it does.

**Comment by vmichalik** [comment]
design best practices are to have a different colour for interactable elements
